Repository weaveworks/tf-controller, pull requests merged in 2023-08, with the labels that each got.

#849 build: remove `nsswitch.conf` creation
  Dockerfile
  planner.Dockerfile
  runner-azure.Dockerfile
  runner.Dockerfile
Labels: area/build

#881 small fix for branch planner to support terraform cloud
  internal/server/polling/terraform.go
Labels: terraform, team/wild-watermelon

#892 Adds OpenSSF badge to Readme
  README.md
Labels: kind/docs, team/wild-watermelon
